name: 'Zola Deploy to Pages '
description: 'Build and deploy a Zola site to GitHub Pages'
author: 'Coelacanthus'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/CoelacanthusHex/zola-deploy-action'
#  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
