# Trigger the workflow on push or pull request
on: [push, pull_request]

name: Tests
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Shellcheck
      uses: docker://koalaman/shellcheck:latest
      with:
        args: ./entrypoint.sh
